### ISSUE TITLE
Add templating support to link titles

### ISSUE THREAD

**Issue by NiklasArbin** [visualeyes/halcyon#18]
It would be nice to have templating support for link titles so that it's possible to have unique titles without having to manually loop over the embedded items.

.AddEmbeddedCollection("children", category.Children, new List<Link>
                {
                    new Link("self", "categories/{Id}", "{Title}", "GET"),
                })

Would you be willing to let me create a pull-request for this?

**Comment by johncmckim** [comment]
Before you do, what's the use case? Wouldn't using templates for titles
hurt discoverability?

I'll be on holidays until the 20/04. I'm happy for you to create a pull
request if there's a good use case for it.

**Comment by NiklasArbin** [comment]
Imagine a list of links for a set of resources, such as books. Then the title of each link should be that book's title.

**Comment by johncmckim** [comment]
@NiklasArbin that's a reasonable reason. Can you send a pull request? Should be a pretty simple one. You should just have to update [this method](https://github.com/visualeyes/halcyon/blob/master/src/Halcyon/HAL/Link.cs#L55).
