### ISSUE TITLE
Support for embedded objects

### ISSUE THREAD

**Issue by andershagvall** [visualeyes/halcyon#22]
I would like to embed a resource object rather than a collection of resource objects. 

Is there a specific reason why only AddEmbeddedCollection is currently supported?

**Comment by johncmckim** [comment]
The only reason that is the case is that I did not realise single resource objects were in the spec. I thought it was only arrays of resources.

I'll add support for single resource object.

**Comment by johncmckim** [comment]
This change has been committed but not release yet.
