### ISSUE TITLE
Accept Header Not Working

### ISSUE THREAD

**Issue by justintconroy** [visualeyes/halcyon#47]
I tried following the instructions in the README to get Halcyon to output plain json if the accept header is simply `application/json` instead of `application/hal+json`, but it doesn't seem to be working. No matter how I fiddle with it, it always returns the HAL formatted results (with a content-type header of `application/json` in the response).

I tried cloning the Halcyon project and running the test project `Halcyon.Tests.SelfHost.Mvc`, which appeared to be setup the way the README described, but I got the same results as with my own project. I feel like I'm missing something important about getting Halcyon to handle the Accept header correctly. Any help would be greatly appreciated.

Thanks.

**Comment by justintconroy** [comment]
I tried setting a breakpoint in `Halcyon.Web.HAL.Json.JsonHalOutputFormatter` line 50, which is in the `WriteAsync` method and running a couple requests against the `Halcyon.Tests.SelfHost.Mvc` test project.

What I found was that if I set the accept header to `application/hal+json`, the breakpoint was hit and the code worked as expected.

When I set the accept header to just `application/json`, the breakpoint never got hit. It would seem that the media type `application/json` is being handled by some other output formatter, and so the logic that checks the media type and chooses which way to format the output is never hit for plain json and thus the response never gets reformatted, I guess?

**Comment by jmpease** [comment]
@justintconroy It looks like the README is slightly outdated.  In order to achieve this behavior I had to explicitly remove the default JsonOutputFormatter:

            services
                .AddMvc()
                .AddMvcOptions(c => {
                    c.OutputFormatters.RemoveType<JsonOutputFormatter>();
                    c.OutputFormatters.Add(new JsonHalOutputFormatter(
                        new string[] { "application/hal+json", "application/vnd.example.hal+json", "application/vnd.example.hal.v1+json" }
                    ));
                });

**Comment by justintconroy** [comment]
Oh yay. That works. Thanks! :-)
