### ISSUE TITLE
Unable to return non-HAL results after disabling default JsonOutputFormatter

### ISSUE THREAD

**Issue by justintconroy** [visualeyes/halcyon#54]
This is sort of related to #47. Removing the default `JsonOutputFormatter` does allow accept headers to work correctly. However, doing so makes returning anything that is not a `HalResponse` (i.e. simply trying to return `Ok(ObjectModel)`) return a `406 Not Acceptable` when the link is accessed.

This doesn't seem totally unreasonable. There's no longer a formatter for `application/json` enabled in the application, and so it seems it's expected that every controller will only return `HalResponse` objects in order to work around this. The problem I have with this is migrating an existing API to start using HAL. We were hoping to make a gradual change to our API, introducing new, compliant endpoints while phasing out older, non-compliant endpoints, but it seems it won't really be possible.

If it's not a design goal of the halcyon team to support such mixed environments, I understand. However, I theorize that it should be possible to register the `JsonHalOutputFormatter` as the handler for `application/json` and produce non-HAL output. I may attempt a pull request doing this.

**Comment by samuelabj** [comment]
That seems a reasonable request and I can't see why we shouldn't support that. If you want to add a PR I'll happily review it.

**Comment by jmpease** [comment]
Ran into that as well...have a potential fix and have been meaning to submit a PR.  Working on that now.

**Comment by justintconroy** [comment]
Oh wow. @jmpease beat me to the punch on a PR. :-)

I wasn't really sure how to deal with `CanWriteResult`. I didn't realize you could just tap into the original `JsonOutputFormatter` so easily.

**Comment by justintconroy** [comment]
I pulled @jmpease's branch, and I can confirm that this fixes the issue for me.

**Comment by samuelabj** [comment]
Thanks both for resolving the issue so quickly.
