### ISSUE TITLE
JsonHalOutputFormatter does not implement IApiResponseTypeMetadataProvider

### ISSUE THREAD

**Issue by jmpease** [visualeyes/halcyon#56]
We're using Swashbuckle [1] for Swagger tooling in our ASP.NET Core-based API project and ran into an issue where the only listed parameter content type available in the Swagger UI [e.g. 2] was "text/plain" when using the JsonHalOutputFormatter, after removing the JsonOutputFormatter (as I did in #48 to fix #47).  After further investigation, it appears this is because the JsonOutputFormatter implements IApiResponseTypeMetadataProvider [3], while the JsonHalOutputFormatter does not.  According to the docs [3]:

> An IOutputFormatter should implement this interface to expose metadata information to an IApiDescriptionProvider.

So assuming that Swashbuckle depends on an implementation of IApiDescriptionProvider, I made a change to the JsonHalOutputFormatter to impl IApiResponseTypeMetadataProvider and everything worked as expected....including listing of configured HAL media types.

Will submit this change as a PR for consideration.

1 - https://github.com/domaindrivendev/Swashbuckle.AspNetCore
https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.aspnetcore.mvc.apiexplorer.iapiresponsetypemetadataprovider
2 - http://petstore.swagger.io/
3 - https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.aspnetcore.mvc.apiexplorer.iapiresponsetypemetadataprovider

**Comment by kikokikok** [comment]
Hi I'm currently facing the same issue with SwashBuckle on ASP.NET Core. I can't seem to figure out how to take into account in SwaggerGen the HAL Model.
Could you advise ?

Thanks a lot !
