### ISSUE TITLE
Collection example

### ISSUE THREAD

**Issue by freeranger** [visualeyes/halcyon#67]
Could we get an example returning a resource collection?
I want to go to `/api/foo` and get back a collection of foo resources, each with a self link.
Something like this:
```
[
    {    
         "_links": {
            "self": { "href": "/api/foo/1" }
         },
        "id": 1,
        "type": "foo"
    },
    {    
         "_links": {
            "self": { "href": "/api/foo/2" }
         },
        "id": 2,
        "type": "foo"
    }
]
```
I can't see any way to do that with HAL though?

**Comment by MarcusKohnert** [comment]
Pass an object that has one property to a HALResponse like so:

```
var searchResult = new
{
      Result = new []
      {
            new HALResponse(new { Id = 1, Type = "foo" })
             .AddLinks(new Link(Link.RelForSelf, "/api/foo/1")),

            new HALResponse(new { Id = 2, Type = "foo" })
            .AddLinks(new Link(Link.RelForSelf, "/api/foo/2")),
       }
};

return new HALResponse(searchResult)
           .AddLinks(new Link(Link.RelForSelf, "/api/foo"));
```

Produces:

```
{
    "result": [
        {
            "id": 1,
            "type": "foo",
            "_links": {
                "self": {
                    "href": "/api/foo/1"
                }
            }
        },
        {
            "id": 2,
            "type": "foo",
            "_links": {
                "self": {
                    "href": "/api/foo/2"
                }
            }
        }
    ],
    "_links": {
        "self": {
            "href": "/api/foo"
        }
    }
}
```

**Comment by freeranger** [comment]
Thanks but that is changing the response type and doesn't seem correct to me anyway - /api/foo/1 gives me a single foo.  /api/foo should give me a collection of foo, not an object that has a property that contains a collection of foo.

I'd have thought my use case is the common one?

**Comment by MarcusKohnert** [comment]
Well it seems this is what the HAL Specification defines:

> A Resource Object represents a resource.

https://tools.ietf.org/html/draft-kelly-json-hal-08#section-4


Here too:

> HAL defines the top level resource having to be a document. Thus a plain List by definition cannot be a HAL document.

https://github.com/spring-projects/spring-hateoas/issues/111#issuecomment-56189639

**Comment by freeranger** [comment]
Hi Marcus,

Interesting, I missed that completely.  It seems then I want something *like* HAL but not really HAL since I want to return a collection of my resource and not some other object - I like the idea that the consumer can choose to ignore the _links section if they want - this is not really part of the business model and is a means to an end (navigation).
If I create this false top level object then the I have this strange situation where /api/foo/1 gives me an instance of foo, but /api/foo does not give me a collection of them - I do have to pay attention to the specific implementation used in order to provide links to the individual resources.

I realise of course that the links are important in a RESTful API but I like the idea that you can ignore them unless you need them.

Taking your code example, this:
```
      Result = new []
      {
            new HALResponse(new { Id = 1, Type = "foo" })
             .AddLinks(new Link(Link.RelForSelf, "/api/foo/1")),

            new HALResponse(new { Id = 2, Type = "foo" })
            .AddLinks(new Link(Link.RelForSelf, "/api/foo/2")),
       }
```
gives me what I want:
```
   [
        {
            "id": 1,
            "type": "foo",
            "_links": {
                "self": {
                    "href": "/api/foo/1"
                }
            }
        },
        {
            "id": 2,
            "type": "foo",
            "_links": {
                "self": {
                    "href": "/api/foo/2"
                }
            }
        }
    ]
```
so thanks for your help
