### ISSUE TITLE
Automatically generate links

### ISSUE THREAD

**Issue by johncmckim** [visualeyes/halcyon#9]
Manually creating links can be a little cumbersome. It would be great if links could be automatically generated from routes or a specialised attribute.

**Comment by NiklasArbin** [comment]
Automatic self-links and templated titles and be able to include the http method would be great. Possibly tying the links strongly using controller and action with lambdas.

**Comment by johncmckim** [comment]
In #17 I've added a method on the `HALResponse` to add a self link:

```c#
var response = new HALResponse(fooBarModel)
        .AddSelfLink(this.Request) // this gets the Request Path - not query string
```

It also adds the self link if it does exist when using the Controller extension method

```c#
return this.HAL(fooModel); // default
return this.HAL(fooModel, new Link[] {
    new Link("self", "/api/foo/{id}") // custom self link
});
return this.HAL(fooModel,  addSelfLinkIfNotExists: false); // turn off self link
```

What is your idea around tying links to controllers + actions with lambdas? How would you use it? I open for ideas on how to improve this.

**Comment by NiklasArbin** [comment]
The initial idea was to be able to bind a link to a controller using halmodel.Link(controller => controler.Get(id)) to be able to have strongly typed links. Might experiment with this later on.
